trydjango/posts/urls.py
from django.urls import path,include
from . import views


app_name="posts"
urlpatterns = [
    path('',views.post_home),
    path('create/',views.post_create,name="create"),
    path('list/',views.post_list,name='list'),
    path('<int:id>/',views.post_detail,name="detail"),
    path('<int:id>/edit/',views.post_update),
    path('<int:id>/delete/',views.post_delete,name="delete")
]

trydjango/trydjango/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('posts/',include('posts.urls')),
]

if settings.DEBUG:
    urlpatterns +=static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)
    

trydjango/posts/models.py
from django.db import models
from django.urls import reverse
# Create your models here.

def upload_location(instance,filename):
    return "%s/%s" %(instance.id,filename)

class Post(models.Model):
    title=models.CharField(max_length=100)
    content=models.TextField()
    image=models.ImageField(upload_to="upload_location",null=True,blank=True,height_field="height_field",width_field="width_field")
    height_field=models.IntegerField(default=0)
    width_field=models.IntegerField(default=0)
    updated=models.DateTimeField(auto_now=True,auto_now_add=False)
    timestamp=models.DateTimeField(auto_now=False,auto_now_add=True)

    def __str__(self):
        return self.title

    def __unicode__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('posts:detail',kwargs={"id":self.id} )
        #return "/posts/%s/" %(self.id)    

    class Meta:
        ordering=["-timestamp"]    

trydjango/posts/forms.py
from django import forms
from .models import Post

class PostForm(forms.ModelForm):
    class Meta:
        model=Post
        fields=["title","content","image"]

trydjango/posts/views.py
from urllib.parse import quote_plus
from django.http import HttpResponse,HttpResponseRedirect,Http404
from django.contrib import messages
from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator
from django.shortcuts import render,get_object_or_404,redirect
from . models import Post
from .forms import PostForm

# Create your views here.
def post_home(request):
    return HttpResponse("<h1>Hello</h1>")

def post_create(request):
    if not request.user.is_staff or not request.user.is_superuser:
        raise Http404
    form=PostForm(request.POST or None,request.FILES or None)
    if form.is_valid():
        instance=form.save(commit=False)
        instance.save()
        messages.success(request,"successfully created")
        return HttpResponseRedirect(instance.get_absolute_url())

    else:
        messages.error(request,"not successfully created")    
    #if request.method=='POST':
     #   print (request.POST.get("content"))
      #  print (request.POST.get("title"))
    return render(request,'post_form.html',{'form':form})
        

def post_list(request):
    if request.user.is_authenticated:
        queryset_list=Post.objects.all()#.order_by("-timestamp")
        paginator = Paginator(queryset_list,10)
        page_request_var="page"
        page=request.GET.get(page_request_var)
        try:
            queryset=paginator.page(page)
        except PageNotAnInteger:
            queryset=paginator.page(1)
        except EmptyPage:
            queryset=paginator.page(paginator.num_pages)

        context={
        "object_list":queryset,    
        "value":"some text value",
        "page_request_var":page_request_var
         }
    else:
        context={
            "value":"normal values"
        }
    return render(request,'post_list.html',context)
    #return HttpResponse("<h1>create</h1>")    

def post_detail(request,id):
    instance=get_object_or_404(Post,id=id)
    share_string=quote_plus(instance.content)
    context={
        "title":instance.title,
        "instance":instance,
        "share_string":share_string
    }
    return render(request,'post_detail.html',context)
    #return HttpResponse("<h1>detail</h1>")

def post_update(request,id):
    instance=get_object_or_404(Post,id=id)
    form=PostForm(request.POST or None,request.FILES or None,instance=instance)
    if form.is_valid():
        instance=form.save(commit=False)
        instance.save()
        messages.success(request,"item saved",extra_tags="added tag")
        return HttpResponseRedirect(instance.get_absolute_url())
    context={
        "title":instance.title,
        "instance":instance,
        "form":form
    }    
    
    return render(request,'post_form.html',context)

def post_delete(request,id):
    instance=get_object_or_404(Post,id=id)
    instance.delete()
    return redirect("posts:list")    



   

trydjango/templates/base.html
{% load staticfiles %}
<html>
    <head>
        <title>{% block title %}Try django {% endblock %}</title>
<!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

<!-- Optional theme -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.1.0/css/all.css" integrity="sha384-lKuwvrZot6UHsBSfcMvOkWwlCMgc0TaWr+30HWe3a4ltaBwTZhyTEggF5tJv8tbt" crossorigin="anonymous">
<link rel="stylesheet" href="{% static 'css/base.css' %}"/>
<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
       
    </head>
    <body>
        {% include "messages_display.html" %}
            
        <div class="container">
        {% block content %}
        <h1>{{value}}</h1>
        <h1>Its working </h1>
       

            {% endblock content %}
        </div>

    </body>
</html>

trydjango/templates/index.html
<html>
    <head>

    </head>
    <body>
        <h1>{{value}}</h1>
        <h1>Its working </h1>

        {% for object in object_list %}
        <div class="col-sm-6 col-md-6">
            <ul><li><h2><a href="{{object.get_absolute_url}}">{{object.title}}</a></h2>
            </li> </ul>
        </div>
            {% endfor %}
        </div>
    </body>
</html>

trydjango/templates/messages_display.html
{% if messages %}
        <div class="messages">

                 <ul class="messages">
                    {% for message in messages %}
                    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
                    {% endfor %}
                </ul>
               
        </div>
        {% endif %}

trydjango/templates/post_detail.html
{% extends 'base.html' %}

{% load urlify %}

{% block title %}  {{instance.title}} {% endblock %}
{% block content %}

<div class="col-sm-6">
        <br><br><br>
        {% if instance.image %}
        <img src="{{instance.image.url}}" class="img-responsive"/>
       {% endif %}
        <h1> {{title}}</h1><br>
        {{instance.title}}---{{instance.timestamp|timesince}}<br>
        {{instance.content}}<br><br>
        {{instance.content|truncatechars:20|urlify}}<br><br>
       # {{share_string}}
       
<br>

        <a href="https://www.facebook.com/sharer/sharer.php?u={{request.build_absolute_uri}}">
                <i class="fab fa-facebook"></i>
                </a>

                <a href="https://twitter.com/home?status={{share_string}}%20{{request.build_absolute_uri}}">
                        <i class="fab fa-twitter"></i>
                        </a>

                        <a href='https://plus.google.com/share?url={{request.build_absolute_uri}}'><i class="fab fa-google-plus-g"></i></a>

</div>
{% endblock content %}

trydjango/templates/post_form.html
{% extends 'base.html' %}
{% block content %}
{{ block.super }}
<div class="col-md-6">       
<h1> Form</h1><br>
       <form method="POST" action="" enctype="multipart/form-data">
          
        {% csrf_token %}
        {{form.as_p}}
        <input type="submit" class="btn btn-primary" value="submit"/>
    </form>
</div>
{% endblock content%}

trydjango/templates/post_list.html
{% extends 'base.html' %}
{% block content %}
        <h1>{{value}}</h1>
        <h1>Its working </h1>
        <p><a href="{% url 'posts:create'%}" class="btn btn-info thumbnail">CREATE NEW POST </a></p>
        <div class="row">
        {% for object in object_list %}

    <div class="col-sm-6 col-md-6">
        <div class="thumbnail">
            {% if object.image %}
                <img src="{{object.image.url}}" class="img-responsive"/>
                {% endif %}
           <div class="caption">
            <h2><a href="{{object.get_absolute_url}}">{{object.title}}</a>  <small>{{object.timestamp|timesince}}</small></h2>
            <p><a href="{{object.get_absolute_url}}" class="btn btn-primary">VIEW</a></p>
            <p><a href="{% url 'posts:delete' object.id %}" class="btn btn-primary">delete</a></p>
        </div>
    </div>
    </div>
            {% endfor %}

            <div class="pagination">
                <span class="step-links">
                    {% if object_list.has_previous %}
                        <a href="?{{page_request_var}}=1">&laquo; first</a>
                        <a href="?{{page_request_var}}={{ object_list.previous_page_number }}">previous</a>
                    {% endif %}
            
                    <span class="current">
                        Page {{ object_list.number }} of {{ object_list.paginator.num_pages }}.
                    </span>
            
                    {% if object_list.has_next %}
                        <a href="?{{page_request_var}}={{ object_list.next_page_number }}">next</a>
                        <a href="?{{page_request_var}}={{ object_list.paginator.num_pages }}">last &raquo;</a>
                    {% endif %}
                </span>
            </div>
        </div>
            {% endblock content %}
        